# ğŸ“Œ ì´ íŒŒì¼ì€ ì˜ˆì‹œ íŒŒì¼ì…ë‹ˆë‹¤. application-local.ymlë¡œ ë³µì‚¬í•´ ì‚¬ìš©í•˜ì„¸ìš”.
# âš ï¸ application-local.ymlì€ Gitì— ì¶”ê°€í•˜ì§€ ë§ˆì„¸ìš” (API í‚¤ ë³´ì•ˆ).
# âœ… ì´ íŒŒì¼ì€ Gitì— ì˜¬ë¼ê°€ë„ ê´œì°®ìŠµë‹ˆë‹¤ (ì‹¤ì œ í‚¤ê°€ ì—†ìŒ).

# ì„œë²„ ì„¤ì •
server:
  port: 8080  # ê°œë°œìš© í¬íŠ¸

# ë°ì´í„°ë² ì´ìŠ¤ ì„¤ì •
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loacompass  # ë¡œì»¬ DB ì£¼ì†Œ
    username: bit1234                   # ë³¸ì¸ DB ì•„ì´ë””
    password: 1234                 # ë³¸ì¸ DB ë¹„ë°€ë²ˆí˜¸
    driver-class-name: com.mysql.cj.jdbc.Driver   # MySQL ë“œë¼ì´ë²„
    profiles:
      active: local


# MyBatis ì„¤ì •
mybatis:
  mapper-locations: classpath:mapper/**/*.xml     # ë§¤í¼ íŒŒì¼ ê²½ë¡œ
  type-aliases-package: com.finalteam.loacompass.entity  # ì—”í‹°í‹° íŒ¨í‚¤ì§€ ìœ„ì¹˜

# ë¡œìŠ¤íŠ¸ì•„í¬ API ì„¤ì •
lostark:
  api:
    base-url: https://api-lostark.game.onstove.com  # ê¸°ë³¸ ì œê³µëœ LostArk API ì£¼ì†Œ
    key: dummy-key  # ğŸ”¥ ì—¬ê¸°ì— ë³¸ì¸ì˜ LostArk API í‚¤ë¥¼ ì…ë ¥í•˜ì„¸ìš”
